### ISSUE TITLE
Issue with latest release.

### ISSUE THREAD

**Issue by ljchakib** [sollenne/angular-fittext#20]
I was working with the version 2.0.8. And after the new release I started receiving the following error:

ERROR in ../angular-fittext/angular-fittext.ts(5,2): Error during template compile of 'AngularFittextModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-fittext/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

ERROR: Job failed: exit status 1

**Comment by sollenne** [comment]
may be a mismatch of angular versions. you have a stackblitz or repo we can look at?

**Comment by sollenne** [comment]
Looks like angular is creating a var that the package is already declaring. https://github.com/angular/angular/issues/21670  if you can update to angular 6, then try using the latest version of this lib, it may work.

**Comment by ljchakib** [comment]
No need to upgrade to Angular 6. For people having the same issue you can just add in yout tsconfig.json:

```
"compilerOptions": {
  ...
  "paths": { "@angular/*": ["../node_modules/@angular/*"] }
}
```

**Comment by sollenne** [comment]
I remember this from a few months ago https://github.com/sollenne/angular-fittext/issues/3#issuecomment-329520902
